trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2.x'
  inputs:
    version: 2.2.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
